// <auto-generated />
using System;
using AskAMech.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AskAMech.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200221104515_Added user photo")]
    partial class Addeduserphoto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AskAMech.Domain.Models.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorId");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<int>("QuestionId");

                    b.HasKey("AnswerId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            AnswerId = 1,
                            AuthorId = "1f7999f-28be-4322-bc69-612ef8cccc5c",
                            Date = new DateTime(2020, 2, 21, 12, 29, 15, 466, DateTimeKind.Local).AddTicks(9761),
                            Description = "fix it",
                            QuestionId = 2
                        },
                        new
                        {
                            AnswerId = 2,
                            AuthorId = "1f7999f-28be-4322-bc69-612ef8cccc5c",
                            Date = new DateTime(2020, 2, 21, 12, 29, 15, 467, DateTimeKind.Local).AddTicks(659),
                            Description = "fix it now",
                            QuestionId = 3
                        },
                        new
                        {
                            AnswerId = 3,
                            AuthorId = "1f7999f-28be-4322-bc69-612ef8cccc5c",
                            Date = new DateTime(2020, 2, 21, 12, 29, 15, 467, DateTimeKind.Local).AddTicks(667),
                            Description = "fix then test it",
                            QuestionId = 4
                        },
                        new
                        {
                            AnswerId = 4,
                            AuthorId = "36b2db51-238e-4224-ad1d-fe3077a5e4e4",
                            Date = new DateTime(2020, 2, 21, 12, 29, 15, 467, DateTimeKind.Local).AddTicks(668),
                            Description = "You can buy from Continental! but the price is just off the roof.. Very expensive",
                            QuestionId = 1
                        },
                        new
                        {
                            AnswerId = 5,
                            AuthorId = "ffc183dc-78c2-413d-96f8-2091600c0b69",
                            Date = new DateTime(2020, 2, 21, 12, 29, 15, 467, DateTimeKind.Local).AddTicks(669),
                            Description = "Super Tyres",
                            QuestionId = 1
                        },
                        new
                        {
                            AnswerId = 6,
                            AuthorId = "1f7999f-28be-4322-bc69-612ef8bbbb5G",
                            Date = new DateTime(2020, 2, 21, 12, 29, 15, 467, DateTimeKind.Local).AddTicks(670),
                            Description = "Goodyear Tyres for new tires, but you can also try your new garage for second hand tyres",
                            QuestionId = 1
                        });
                });

            modelBuilder.Entity("AskAMech.Domain.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FullName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<byte[]>("UserPhoto");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "1f7999f-28be-4322-bc69-612ef8bbbb5G",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c18909f6-ea08-4f14-a819-74750607e620",
                            Email = "lindco@outlook.com",
                            EmailConfirmed = true,
                            FullName = "lindokuhle",
                            LockoutEnabled = true,
                            NormalizedEmail = "LINDCHO@OUTLOOK.COM",
                            NormalizedUserName = "LINDCHO@OUTLOOK.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEKGJW6gAMtcOK+HH2phjyFSosZjyexbheSbFtgc6IYtspAcTAmPe9MwjitV7xe8gLQ==",
                            PhoneNumber = "0746009500",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "61757722-34cf-48d7-b297-ee2b14538f52",
                            TwoFactorEnabled = false,
                            UserName = "lindco@outlook.com"
                        },
                        new
                        {
                            Id = "1f7999f-28be-4322-bc69-612ef8cccc5c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "be808c23-2b6d-4c61-8426-e82187382015",
                            Email = "askamech@gmail.com",
                            EmailConfirmed = true,
                            FullName = "khanyisile",
                            LockoutEnabled = true,
                            NormalizedEmail = "ASKAMECH@GMAIL.COM",
                            NormalizedUserName = "ASKAMECH@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEKGJW6gAMtcOK+HH2phjyFSosZjyexbheSbFtgc6IYtspAcTAmPe9MwjitV7xe8gLQ==",
                            PhoneNumber = "0746009500",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "92e2613a-e2f5-4e3f-b4ba-4f1bdcaf0937",
                            TwoFactorEnabled = false,
                            UserName = "askamech@gmail.com"
                        },
                        new
                        {
                            Id = "36b2db51-238e-4224-ad1d-fe3077a5e4e4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bf89a831-e5d7-4712-9af8-9e3a384b49ec",
                            Email = "sam@gmail.com",
                            EmailConfirmed = true,
                            FullName = "samkelo",
                            LockoutEnabled = true,
                            NormalizedEmail = "SAM@GMAIL.COM",
                            NormalizedUserName = "SAM@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEKGJW6gAMtcOK+HH2phjyFSosZjyexbheSbFtgc6IYtspAcTAmPe9MwjitV7xe8gLQ==",
                            PhoneNumber = "0746009500",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "82396159-6c22-416c-bc07-2fee39a1017d",
                            TwoFactorEnabled = false,
                            UserName = "sam@gmail.com"
                        },
                        new
                        {
                            Id = "ffc183dc-78c2-413d-96f8-2091600c0b69",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "754d698d-af9b-42b6-acc0-ca05c1354a5a",
                            Email = "lindo1@ymail.com",
                            EmailConfirmed = true,
                            FullName = "samkelo",
                            LockoutEnabled = true,
                            NormalizedEmail = "LINDO1@YMAIL.COM",
                            NormalizedUserName = "LINDO1@YMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEKGJW6gAMtcOK+HH2phjyFSosZjyexbheSbFtgc6IYtspAcTAmPe9MwjitV7xe8gLQ==",
                            PhoneNumber = "0746009500",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "b63cd8e8-34b5-499e-8a99-a336b009e6eb",
                            TwoFactorEnabled = false,
                            UserName = "lindo1@ymail.com"
                        });
                });

            modelBuilder.Entity("AskAMech.Domain.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AcceptedAnswerId");

                    b.Property<string>("AuthorId");

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("Description");

                    b.Property<DateTime>("LastModified");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedAnswerId")
                        .IsUnique()
                        .HasFilter("[AcceptedAnswerId] IS NOT NULL");

                    b.HasIndex("AuthorId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = "1f7999f-28be-4322-bc69-612ef8bbbb5c",
                            DateCreated = new DateTime(2020, 2, 21, 11, 45, 15, 465, DateTimeKind.Local).AddTicks(6873),
                            Description = "I need to know where can i buy a strong tire.",
                            LastModified = new DateTime(2020, 2, 21, 12, 35, 15, 466, DateTimeKind.Local).AddTicks(6981),
                            Title = "where to buy a strong tire"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = "1f7999f-28be-4322-bc69-612ef8bbbb5G",
                            DateCreated = new DateTime(2020, 2, 21, 9, 45, 15, 466, DateTimeKind.Local).AddTicks(7510),
                            Description = "I just bought a tire but don;t know how to fit it in my car.",
                            LastModified = new DateTime(2020, 2, 21, 12, 43, 15, 466, DateTimeKind.Local).AddTicks(7516),
                            Title = "How to fit a tire"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = "36b2db51-238e-4224-ad1d-fe3077a5e4e4",
                            DateCreated = new DateTime(2019, 12, 23, 12, 45, 15, 466, DateTimeKind.Local).AddTicks(7520),
                            Description = "I bought brackpads but don't know how to fix it.",
                            LastModified = new DateTime(2020, 1, 22, 12, 45, 15, 466, DateTimeKind.Local).AddTicks(7522),
                            Title = "How to fit brackes"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = "ffc183dc-78c2-413d-96f8-2091600c0b69",
                            DateCreated = new DateTime(2019, 12, 23, 12, 45, 15, 466, DateTimeKind.Local).AddTicks(7523),
                            Description = "my cra is making a noise i think i need to replace cv's.",
                            LastModified = new DateTime(2020, 2, 21, 12, 35, 15, 466, DateTimeKind.Local).AddTicks(7524),
                            Title = "CV problem"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = "ffc183dc-78c2-413d-96f8-2091600c0b69",
                            DateCreated = new DateTime(2019, 12, 23, 12, 45, 15, 466, DateTimeKind.Local).AddTicks(7526),
                            Description = "i bought this brakes two months ago but it seams like they are not original.",
                            LastModified = new DateTime(2020, 2, 21, 12, 29, 15, 466, DateTimeKind.Local).AddTicks(7526),
                            Title = "My car brakes are not working"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("AskAMech.Domain.Models.Answer", b =>
                {
                    b.HasOne("AskAMech.Domain.Models.ApplicationUser", "Author")
                        .WithMany("Answers")
                        .HasForeignKey("AuthorId");

                    b.HasOne("AskAMech.Domain.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AskAMech.Domain.Models.Question", b =>
                {
                    b.HasOne("AskAMech.Domain.Models.ApplicationUser", "Author")
                        .WithMany("Questions")
                        .HasForeignKey("AuthorId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AskAMech.Domain.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AskAMech.Domain.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AskAMech.Domain.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AskAMech.Domain.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
