// <auto-generated />
using System;
using AskAMech.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AskAMech.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200217133047_AddAnswers")]
    partial class AddAnswers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AskAMech.Domain.Models.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorId");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<int>("QuestionId");

                    b.HasKey("AnswerId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            AnswerId = 1,
                            AuthorId = "1f7999f-28be-4322-bc69-612ef8bbbb5c",
                            Date = new DateTime(2020, 2, 17, 15, 14, 46, 959, DateTimeKind.Local).AddTicks(2021),
                            Description = "fix it",
                            QuestionId = 2
                        },
                        new
                        {
                            AnswerId = 2,
                            AuthorId = "1f7999f-28be-4322-bc69-612ef8bbbb5c",
                            Date = new DateTime(2020, 2, 17, 15, 14, 46, 959, DateTimeKind.Local).AddTicks(3103),
                            Description = "fix it now",
                            QuestionId = 3
                        },
                        new
                        {
                            AnswerId = 3,
                            AuthorId = "1f7999f-28be-4322-bc69-612ef8bbbb5c",
                            Date = new DateTime(2020, 2, 17, 15, 14, 46, 959, DateTimeKind.Local).AddTicks(3120),
                            Description = "fix then test it",
                            QuestionId = 4
                        },
                        new
                        {
                            AnswerId = 4,
                            AuthorId = "36b2db51-238e-4224-ad1d-fe3077a5e4e4",
                            Date = new DateTime(2020, 2, 17, 15, 14, 46, 959, DateTimeKind.Local).AddTicks(3122),
                            Description = "You can buy from Continental! but the price is just off the roof.. Very expensive",
                            QuestionId = 1
                        },
                        new
                        {
                            AnswerId = 5,
                            AuthorId = "ffc183dc-78c2-413d-96f8-2091600c0b69",
                            Date = new DateTime(2020, 2, 17, 15, 14, 46, 959, DateTimeKind.Local).AddTicks(3123),
                            Description = "Super Tyres",
                            QuestionId = 1
                        },
                        new
                        {
                            AnswerId = 6,
                            AuthorId = "1f7999f-28be-4322-bc69-612ef8bbbb5G",
                            Date = new DateTime(2020, 2, 17, 15, 14, 46, 959, DateTimeKind.Local).AddTicks(3125),
                            Description = "Goodyear Tyres for new tires, but you can also try your new garage for second hand tyres",
                            QuestionId = 1
                        });
                });

            modelBuilder.Entity("AskAMech.Domain.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FullName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("PictureUrl");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "1f7999f-28be-4322-bc69-612ef8bbbb5G",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9aad1f81-e750-49cd-ad8d-03a2747ccf9b",
                            Email = "lindco@outlook.com",
                            EmailConfirmed = true,
                            FullName = "lindokuhle",
                            LockoutEnabled = true,
                            NormalizedEmail = "LINDCHO@OUTLOOK.COM",
                            NormalizedUserName = "LINDCHO@OUTLOOK.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEKGJW6gAMtcOK+HH2phjyFSosZjyexbheSbFtgc6IYtspAcTAmPe9MwjitV7xe8gLQ==",
                            PhoneNumber = "0746009500",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "2c33362b-5e29-41d4-a063-2bb0daab231f",
                            TwoFactorEnabled = false,
                            UserName = "lindco@outlook.com"
                        },
                        new
                        {
                            Id = "1f7999f-28be-4322-bc69-612ef8bbbb5c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c8ca99fa-c63d-4687-92a7-a6b8ffd9f3b3",
                            Email = "askamech@gmail.com",
                            EmailConfirmed = true,
                            FullName = "khanyisile",
                            LockoutEnabled = true,
                            NormalizedEmail = "ASKAMECH@GMAIL.COM",
                            NormalizedUserName = "ASKAMECH@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEKGJW6gAMtcOK+HH2phjyFSosZjyexbheSbFtgc6IYtspAcTAmPe9MwjitV7xe8gLQ==",
                            PhoneNumber = "0746009500",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "5ed77261-3744-49d2-a77f-e375a0e316e4",
                            TwoFactorEnabled = false,
                            UserName = "askamech@gmail.com"
                        },
                        new
                        {
                            Id = "36b2db51-238e-4224-ad1d-fe3077a5e4e4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e3de6acd-d55d-4f91-a3d6-436e94c6e3b7",
                            Email = "sam@gmail.com",
                            EmailConfirmed = true,
                            FullName = "samkelo",
                            LockoutEnabled = true,
                            NormalizedEmail = "SAM@GMAIL.COM",
                            NormalizedUserName = "SAM@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEKGJW6gAMtcOK+HH2phjyFSosZjyexbheSbFtgc6IYtspAcTAmPe9MwjitV7xe8gLQ==",
                            PhoneNumber = "0746009500",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "12fda695-a9df-4ee5-a7ba-9b59425196df",
                            TwoFactorEnabled = false,
                            UserName = "sam@gmail.com"
                        },
                        new
                        {
                            Id = "ffc183dc-78c2-413d-96f8-2091600c0b69",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "340aacde-e683-48b2-9ada-7540eaef63f7",
                            Email = "lindo1@ymail.com",
                            EmailConfirmed = true,
                            FullName = "samkelo",
                            LockoutEnabled = true,
                            NormalizedEmail = "LINDO1@YMAIL.COM",
                            NormalizedUserName = "LINDO1@YMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEKGJW6gAMtcOK+HH2phjyFSosZjyexbheSbFtgc6IYtspAcTAmPe9MwjitV7xe8gLQ==",
                            PhoneNumber = "0746009500",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "fd68d76c-aa92-4f50-8a00-61242845f3cb",
                            TwoFactorEnabled = false,
                            UserName = "lindo1@ymail.com"
                        });
                });

            modelBuilder.Entity("AskAMech.Domain.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AcceptedAnswerId");

                    b.Property<string>("AuthorId");

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("Description");

                    b.Property<DateTime>("LastModified");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedAnswerId")
                        .IsUnique()
                        .HasFilter("[AcceptedAnswerId] IS NOT NULL");

                    b.HasIndex("AuthorId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = "1f7999f-28be-4322-bc69-612ef8bbbb5c",
                            DateCreated = new DateTime(2020, 2, 17, 14, 30, 46, 957, DateTimeKind.Local).AddTicks(4587),
                            Description = "I need to know where can i buy a strong tire.",
                            LastModified = new DateTime(2020, 2, 17, 15, 20, 46, 958, DateTimeKind.Local).AddTicks(8476),
                            Title = "where to buy a strong tire"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = "1f7999f-28be-4322-bc69-612ef8bbbb5G",
                            DateCreated = new DateTime(2020, 2, 17, 12, 30, 46, 958, DateTimeKind.Local).AddTicks(9080),
                            Description = "I just bought a tire but don;t know how to fit it in my car.",
                            LastModified = new DateTime(2020, 2, 17, 15, 28, 46, 958, DateTimeKind.Local).AddTicks(9092),
                            Title = "How to fit a tire"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = "36b2db51-238e-4224-ad1d-fe3077a5e4e4",
                            DateCreated = new DateTime(2019, 12, 19, 15, 30, 46, 958, DateTimeKind.Local).AddTicks(9098),
                            Description = "I bought brackpads but don't know how to fix it.",
                            LastModified = new DateTime(2020, 1, 18, 15, 30, 46, 958, DateTimeKind.Local).AddTicks(9100),
                            Title = "How to fit brackes"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = "ffc183dc-78c2-413d-96f8-2091600c0b69",
                            DateCreated = new DateTime(2019, 12, 19, 15, 30, 46, 958, DateTimeKind.Local).AddTicks(9102),
                            Description = "my cra is making a noise i think i need to replace cv's.",
                            LastModified = new DateTime(2020, 2, 17, 15, 20, 46, 958, DateTimeKind.Local).AddTicks(9103),
                            Title = "CV problem"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = "ffc183dc-78c2-413d-96f8-2091600c0b69",
                            DateCreated = new DateTime(2019, 12, 19, 15, 30, 46, 958, DateTimeKind.Local).AddTicks(9105),
                            Description = "i bought this brakes two months ago but it seams like they are not original.",
                            LastModified = new DateTime(2020, 2, 17, 15, 14, 46, 958, DateTimeKind.Local).AddTicks(9106),
                            Title = "My car brakes are not working"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("AskAMech.Domain.Models.Answer", b =>
                {
                    b.HasOne("AskAMech.Domain.Models.ApplicationUser", "Author")
                        .WithMany("Answers")
                        .HasForeignKey("AuthorId");

                    b.HasOne("AskAMech.Domain.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AskAMech.Domain.Models.Question", b =>
                {
                    b.HasOne("AskAMech.Domain.Models.ApplicationUser", "Author")
                        .WithMany("Questions")
                        .HasForeignKey("AuthorId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AskAMech.Domain.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AskAMech.Domain.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AskAMech.Domain.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AskAMech.Domain.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
